### ISSUE TITLE
Applying Full-yolo to yolo_lite

### ISSUE THREAD

**Issue by kuochiyoug** [chrisgundling/yolo_light#2]
Hi! I am currently use this code with tiny-yolo-voc now, however I also want to compare with full-yolo-voc.

Since the darkflow should run on python3 but not python2, the ROS always runs on python2 makes me always occur error when I trying to load the full-yolo-voc.cfg structure. 

Anyone have the solutions?

**Comment by chrisgundling** [comment]
Hi @kuochiyoug,

ROS 1.0 is only compatible with Python 2. There might be a complicated workaround to use Python 3, but I would recommend either using Python 2 with ROS 1.0, or try ROS 2.0 with Python 3. I believe that ROS 2.0 is not officially released, but is available. (https://github.com/ros2/ros2/wiki)

Hope you find a solution,

Chris
